### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by marceloarocha** [noharm-ai/getname-api#6]
- Uma aplicação única que conecta nos bancos de dados Postgres, Oracle e MSSQL.
- A aplicação deve ser configurada por váriáveis de ambiente que serão definidas no docker compose.
- Avaliar atualizar da imagem docker para https://github.com/tiangolo/meinheld-gunicorn-flask-docker

**Comment by arthurtabbal** [comment]
Ok, @marceloarocha !

**Comment by marceloarocha** [comment]
#9
